---
title: "ZARBITRAGE"
output:
  flexdashboard::flex_dashboard:
    source_code: "https://github.com/riazarbi/zarbitrage"
    navbar:
      - { icon: "fa-database", href: "https://riazarbi.github.io/zarbitrage/documentation.html", align: right }
---

```{r setup, echo=F, results='hide'}
library(duckdb)
# Libraries
library(ggplot2)
library(dplyr)
library(plotly)
library(lubridate)
options(scipen=999)
```

```{r connect, echo=F, results='hide'}
# to start an in-memory database
con <- dbConnect(duckdb::duckdb(), dbdir = "../data/warehouse.duckdb", read_only=TRUE)
res <- dbGetQuery(con, "TABLE returns") %>% as_tibble()
```


BTC / ZAR
=====================================  

```{r plot_btc, echo=F}
b <- res %>%
filter(hour > now() - days(90)) %>%
filter(principal == 300000) %>%
filter(kraken == "XXBTZUSD") %>%
mutate(principal = paste("ZAR", as.factor(principal))) %>%
rename(Pair=kraken) %>%
ggplot(aes(x = hour, y = return)) + 
  geom_line(aes(color = Pair), size = 0.5) + 
  scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + 
  ggtitle("Estimated % return for BTCUSD for ZAR300k, last 90 days") + # for the main title
  xlab("Hour") + # for the x axis label
  ylab("Percentage Return") + # for the y axis label
  facet_wrap(~principal, ncol = 2) + theme_bw() +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank())

```



```{r plotly_btc, fig.width=20, fig.height=20} 
ggplotly(b)
```

ZAR / USD
=====================================  

```{r plot_zar, echo=F}
b <- dbGetQuery(con, "select * from  int_yahoo where pair='USDZAR'") %>% 
as_tibble() %>%
filter(hour > now() - days(14)) %>%
rename(Pair=pair) %>%
ggplot(aes(x = hour, y = yahoo_ask)) + 
  geom_line(aes(color = Pair), size = 0.5) + 
  scale_y_continuous() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + 
  ggtitle("USDZAR ask, last 14 days") + # for the main title
  xlab("Hour") + # for the x axis label
  ylab("Rate") + # for the y axis label
  theme_bw() +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank())

```

```{r plotly_zar, fig.width=20, fig.height=20} 
ggplotly(b)
```



All
=====================================  

```{r plot, echo=F}
g <- res %>%
filter(hour > now() - days(14)) %>%
mutate(principal = paste("ZAR", as.factor(principal))) %>%
rename(Pair=kraken) %>%
ggplot(aes(x = hour, y = return)) + 
  geom_line(aes(color = Pair), size = 0.5) + 
  scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + 
  ggtitle("Estimated % return per trading pair for varying principals, last 14 days") + # for the main title
  xlab("Hour") + # for the x axis label
  ylab("Percentage Return") + # for the y axis label
  facet_wrap(~principal, ncol = 2) + theme_bw() +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank())

```

```{r plotly, fig.width=20, fig.height=20} 
ggplotly(g)
```
```{r disconnect, echo=F, results='hide'}
dbDisconnect(con, shutdown=T)
```
