name: extract

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '*/20 * * * *'

env:
  GITHUB_PAT: ${{ secrets.GH_PAT }}

jobs:
  make_run:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pull and run
        run: |
          make extract
      -
        name: Commit and push
        run: |-
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
